version: '3.3'

services:
  db:
    command: --default-authentication-plugin=mysql_native_password
    image: mysql:8.0.29
    restart: always
    volumes:
    - ./db_backup_snapshot.sql:/docker-entrypoint-initdb.d/datadump.sql
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3306:3306"